from pydantic import BaseModel, Field, field_validator
from pydantic_core.core_schema import ValidationInfo


class EnrichmentResponse(BaseModel):
    enriched_article: str = Field(
        ..., description="The enriched markdown content generated by the assistant."
    )
    explanation: str = Field(
        ...,
        description="Brief explanation of enrichment decisions, may be reused or ignored by QA step.",
    )


class QAEnrichedArticle(BaseModel):
    enriched_article: str = Field(
        ..., description="The full enriched article content in Markdown format."
    )
    has_two_links: bool = Field(
        ..., description="Exactly two inline links are present."
    )
    has_two_images: bool = Field(
        ..., description="Exactly two images are present in the correct positions."
    )
    has_valid_alt_text: bool = Field(
        ..., description="Alt text exists, is descriptive, and under 125 characters."
    )
    follows_brand_voice: bool = Field(
        ..., description="Brand tone and voice were followed."
    )
    accepted: bool = Field(..., description="True only if all above are true.")
    score: float = Field(
        ..., ge=0, le=10, description="Rating from 0–10 based on enrichment quality."
    )
    explanation: str = Field(
        ...,
        min_length=5,
        description="A detailed explanation from the AI about its reasoning for the article's enrichment, \
                             including choices made for link and image placement, adherence to brand guidelines, and self-correction insights if previous QA failed. \
                             This field is crucial for debugging and improving AI performance.",
    )

    @field_validator("accepted")
    @classmethod
    def accept_only_if_all_true(cls, v, info: ValidationInfo):
        values = info.data
        required_flags = [
            "has_two_links",
            "has_two_images",
            "has_valid_alt_text",
            "follows_brand_voice",
        ]
        if any(values.get(flag) is False for flag in required_flags):
            if v:
                raise ValueError("Cannot accept article if any pass criteria is false.")
            return False
        return v

    @field_validator("score")
    @classmethod
    def ensure_score_matches_acceptance(cls, v, info: ValidationInfo):
        values = info.data
        accepted = values.get("accepted", False)
        if accepted and v < 7:
            raise ValueError("Accepted articles must score at least 7.")
        if not accepted and v >= 7:
            raise ValueError("Rejected articles must score below 7.")
        return v
